export const FETCH_REQUESTS_REQUESTED = "FETCH_REQUESTS_REQUESTED";
export const FETCH_REQUESTS_SUCCESS = "FETCH_REQUESTS_SUCCESS";
export const FETCH_REQUESTS_FAILED = "FETCH_REQUESTS_FAILED";

export const DELETE_REQUEST_REQUESTED = "DELETE_REQUEST_REQUESTED";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAILED = "DELETE_REQUEST_FAILED";